name: at_utils
description: A Dart library that contains various utility classes such as atSign, atmetadata, configuration, and logger.
version: 3.0.12
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev
documentation: https://docs.atsign.com/


environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  logging: ^1.0.1
  yaml: ^3.1.0
  crypto: ^3.0.1
  at_commons: ^3.0.42
  collection: ^1.15.0

dependency_overrides:
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: packages/at_commons
      ref: dart-3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.0
  test_process: ^2.0.0
