name: at_commons
description: A library of Dart and Flutter utility classes that are used across other components of the atPlatform.
version: 3.0.49
repository: https://github.com/atsign-foundation/at_tools
homepage: https://atsign.dev

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  uuid: ^3.0.6
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  test_process: ^2.0.2
