name: at_auth
description: Package that implements common logic for onboarding/authenticating an atsign to a secondary server
version: 1.0.0
homepage: https://atsign.com/
repository: https://github.com/atsign-foundation/at_libraries

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  at_commons: ^3.0.56
  at_lookup: ^3.0.40
  at_chops: ^1.0.5
  at_utils: ^3.0.15

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.7
  mocktail: ^0.3.0
