name: at_register
description: Package that has code to interact with the AtRegistrar API
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

dependencies:
  at_commons: ^4.0.1
  at_utils: ^3.0.16
  http: ^1.2.0
  mocktail: ^1.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
