name: example
description: Simple CLI examples using at_cli_commons
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  at_cli_commons:
    path: ..

dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: dep_upgrades
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
