name: at_enrollment_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  crypton: ^2.0.1
  encrypt: ^5.0.0
  at_auth: ^1.0.1
  at_chops: ^1.0.6
  at_onboarding_cli:
    path: ../../../at_onboarding_cli
  at_cli:
    path: ../../../../../at_tools/packages/at_cli
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
