name: at_cli_commons
description: Library of useful stuff when building cli programs which use the AtClient SDK
version: 1.0.4

repository: https://github.com/atsign-foundation/at_libraries/tree/trunk/packages/at_cli_commons
homepage: https://docs.atsign.com/

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  args: ^2.4.2
  at_client: ^3.0.68
  at_onboarding_cli: ^1.4.0
  at_utils: ^3.0.15
  chalkdart: ^2.0.9
  version: ^3.0.2
  logging: ^1.2.0
  meta: ^1.11.0

dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: dep_upgrades
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
